url:
baseurl: /codex-portfolio-template/

# Site settings
title: Website Title
email: griffin98@protonmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/griffin98
  - title: bitbucket
    url: http://bitbucket.org/griffin98
  - title: github
    url: http://github.com/griffin98

# Build settings
markdown: kramdown
permalink: pretty
